name: Create a comment on new issue

on:
  issues:
    types: [opened]

jobs:
  comment-with-action:
    runs-on: ubuntu-latest
    permissions:
      issues: write        # â† Cáº¦N THIáº¾T Ä‘á»ƒ táº¡o comment
    steps:
      - name: Dump GitHub context
        run: echo '${{ toJSON(github.event) }}' | jq .
        shell: bash

      - name: Create comment with Action
        uses: peter-evans/create-or-update-comment@v5
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            This is a multi-line test comment
            - With GitHub **Markdown** âœ¨
            - Created by [create-or-update-comment][1]

            [1]: https://github.com/peter-evans/create-or-update-comment
          reactions: '+1'

  create-comment-with-api:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Create comment with API
        run: |
          gh api -X POST \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments \
            -f body='Comment created via GitHub API call (not action) ğŸ‰'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   # â† Sá»­a tÃªn secret
